"""remove created and modified by in employee table

Revision ID: 227d3d51b564
Revises: 3665dd68f178
Create Date: 2024-11-12 18:49:53.788686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '227d3d51b564'
down_revision: Union[str, None] = '3665dd68f178'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee_images', 'modified_by')
    op.drop_column('employee_images', 'created_by')
    op.drop_column('employees', 'modified_by')
    op.drop_column('employees', 'created_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('created_by', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('modified_by', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('employee_images', sa.Column('created_by', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('employee_images', sa.Column('modified_by', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
